name: deploy

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout 🛎️
          uses: actions/checkout@v2.3.1

        - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
          run: |
            npm install
            npm run buildgithub
            cp dist/cv/index.html dist/cv/404.html
            echo ===========================
            ls dist/cv

        - name: Deploy 🚀
          uses: JamesIves/github-pages-deploy-action@4.1.5
          with:
            branch: gh-pages # The branch the action should deploy to.
            folder: dist/cv # The folder the action should deploy.

  build-deploy-heroku:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "ibram-resume" #Must be unique in Heroku
            heroku_email: "abramreda815@gmail.com"
